project:
  type: website
  output-dir: .

website:
  title: "Steven García Goñi"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true
