---
title: "Material de clases"
format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: false
    code-fold: false
---

Aquí encontrará las clases de los diferentes cursos del área de conocimiento Estadística, de la Escuela de Ingeniería Industrial

## II-1120 Estadística para Ingeniería Industrial I

1.  [Introducción a la estadística](clases/II-1120_01_Introducción_estadística.html){target="_blank"}

2. [Fundamentos de muestreo y manejo de datos](clases/II-1120_02_Fundamentos_muestreo.html){target="_blank"}

3. [Descripción de datos (Estadística descriptiva)](clases/II-1120_03_Descripción_datos.html){target="_blank"}

## II-1123 Estadística para Ingeniería Industrial II

1. [Fundamentos de muestreo y manejo de datos](clases/II-1120_02_Fundamentos_muestreo.html){target="_blank"}

2. [Pruebas de bondad de ajuste para distribuciones](clases/II-1123_02_Bondad_ajuste.html){target="_blank"}

3. [Estadística no paramétrica para una o dos variables](clases/II-1123_03_Est_no_paramétrica.html){target="_blank"}