---
title: "Infografías"
format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: false
    code-fold: false
    collapse-sections: true
    collapse-open: false
---

```{r echo=FALSE}

library(fontawesome)

```

En esta sección encontrará infografías organizadas en pestañas para facilitar su consulta. Todo el material, exceptuando aquel etiquetado como externo, es de mi autoría.

## Inferencia estadística `r fontawesome::fa("chalkboard-user")`

* [Comprendiendo los valores P](infografias/Comprendiendo el valor P.pdf){target="_blank"} 

Esta infografía presenta la definición del valor P, criterios para su interpretación y una guía para la elección del nivel de significancia ($\alpha$). 

* [El mito del $n \ge 30$](infografias/dogma_n_30.pdf){target="_blank"} 

La cifra 30 se ha convertido en una especie de "*número mágico*" que, supuestamente, garantiza la normalidad gracias al Teorema del Límite Central (TLC). Sin embargo, esta noción es peligrosa.

* [Diagrama de decisión para pruebas de hipótesis](infografias/esquema_PH.pdf){target="_blank"} 

Este diagrama le puede ayudar a tomar decisiones sobre la prueba de hipótesis que debe llevarse a cabo. 