<!DOCTYPE html>
<html lang="es"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/quarto-contrib/videojs/video.min.js"></script>
<link href="site_libs/quarto-contrib/videojs/video-js.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Steven García Goñi steven.garciagoni@ucr.ac.cr">
  <title>Descripción de datos</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link rel="stylesheet" href="custom.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

  <link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

  <script src="site_libs/plotly-binding-4.10.4/plotly.js"></script>

  <script src="site_libs/typedarray-0.1/typedarray.min.js"></script>

  <script src="site_libs/jquery-3.5.1/jquery.min.js"></script>

  <link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">

  <script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>

  <link href="site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">

  <script src="site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>

</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section class="quarto-title-block center">
  <h1 class="title">Descripción de datos</h1>
  <p class="subtitle"><a href="https://stevenggoni.github.io/clases/II-1120_03_Descripción_datos.pdf">Versión PDF</a> <br> II-1120 Estadística para Ingeniería Industrial I</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Steven García Goñi<br><a href="mailto:steven.garciagoni@ucr.ac.cr">steven.garciagoni@ucr.ac.cr</a> 
</div>
</div>
</div>

  <p class="date">18 de febrero de 2026</p>
</section>
<section class="slide level2 bloques">
<h2>Agenda</h2>
<ul>
<li>Preguntas generadoras</li>
<li>Visualización de datos</li>
<li>Técnicas para describir:
<ul>
<li>Variables categóricas</li>
<li>Variables cuantitativas</li>
<li>Visualizaciones recomendadas</li>
</ul></li>
<li>Consejos para la presentación de datos
<ul>
<li>Gráficos tendenciosos o erróneos</li>
<li>Cuadros y gráficos estadísticos</li>
</ul></li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>Preguntas generadoras</h2>
<ul>
<li>¿Cuándo usar cada tipo de técnicas para describir variables?</li>
<li>¿Cuándo usar las medidas de posición, dispersión y forma?</li>
<li>¿Por qué es importante estudiar la dispersión de los datos?</li>
<li>¿Por qué es importante estudiar la forma de los datos?</li>
<li>¿Cómo escoger el gráfico adecuado para el tipo de datos que tengo?</li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>¡Recuerde!</h2>
<div class="columns">
<div class="column" style="width:55%;">
<ul>
<li><p>Las variables se pueden clasificar por tipo: <em>Cuantitativa</em> y <em>Cualitativa</em>, así como por niveles de medición: <em>Nominal</em>, <em>Ordinal</em>, <em>Intervalo</em> y <em>Razón.</em></p></li>
<li><p>Éstas determinan como se deben recoger y analizar lo datos. Es decir, rigen los cálculos que se deben llevar a cabo.</p></li>
<li><p>La validez de las conclusiones depende de la fiabilidad de la recolección de datos y de las técnicas de análisis empleadas.</p></li>
</ul>
</div><div class="column img-fit" style="width:45%;">
<p><img data-src="img/diagrama.png"></p>
</div></div>
</section>
<section>
<section class="title-slide slide level1 center">
<h1>Visualización de datos</h1>

</section>
<section class="slide level2 bloques">
<h2>Visualización</h2>
<div class="columns">
<div class="column" style="text-align: center; font-size: 1.5em;">
<p>La visualización es una <span class="hi">actividad humana fundamental</span>. Una buena visualización mostrará cosas que no se esperaban o hará surgir nuevas preguntas acerca de los datos. También puede dar pistas acerca de si se están haciendo las preguntas equivocadas o si se necesita recolectar datos diferentes.</p>
<blockquote>
<p>“<span class="hi">Un simple gráfico ha brindado más información a la mente del analista de datos que cualquier otro dispositivo</span>”. - <em>John Tukey</em></p>
</blockquote>
</div></div>
</section></section>
<section>
<section class="title-slide slide level1 center">
<h1>Medidas para <span class="hi">una</span> variable <span class="hi">cualitativa</span></h1>

</section>
<section class="slide level2 bloques">
<h2>Ejemplo</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Un usuario en <a href="https://www.reddit.com/r/Ticos/comments/yz1ujt/mejor_fresco_leche/" target="_blank">Reddit (enlace)</a> pregunta a la comunidad:
<ul>
<li>¿Cuál es el mejor sabor de fresco leche? Con lo que obtiene estos resultados:</li>
</ul></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top" style="margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Sabor</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Votos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chocolate</td>
<td style="text-align: right;">103</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vainilla</td>
<td style="text-align: right;">92</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fresa</td>
<td style="text-align: right;">72</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>Discuta con la persona docente y sus compañeros y compañeras:
<ul>
<li>¿Qué nivel de medición fue usado?</li>
<li>¿Cuál es la muestra? Descríbala</li>
<li>¿Cuál es la población?</li>
<li>¿Qué tipo de muestreo fue usado?</li>
<li>¿Este tipo de recolección de datos introduce algún <span class="hi">sesgo</span>?</li>
</ul></li>
</ul>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Ejemplo</h2>
<div class="columns">
<div class="column" style="width:100%;">
<ul>
<li>Las variables categóricas, de nivel nominal, solo pueden ser agrupadas y contadas (esto se conoce como <span class="hi">tabla de frecuencia</span>). Además, se pueden obtener proporciones.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top" style="margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Sabor</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Votos</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Proporción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chocolate</td>
<td style="text-align: right;">103</td>
<td style="text-align: right;">0.386</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vainilla</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">0.345</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fresa</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">0.270</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Ejemplo - Visualización</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Las variables categóricas se pueden representar de muchas formas. Dos de ellas son:</p>
<div class="cell">
<div class="cell-output-display">
<div id="htmlwidget-cc4d58a0f367c3baa62f" style="width:850px;height:500px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-cc4d58a0f367c3baa62f">{"x":{"visdat":{"5c5856217e26":["function () ","plotlyVisDat"]},"cur_data":"5c5856217e26","attrs":{"5c5856217e26":{"labels":{},"values":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"pie"}},"layout":{"width":850,"height":500,"margin":{"b":40,"l":60,"t":25,"r":10},"paper_bgcolor":"#F1F5F5","plot_bgcolor":"#F1F5F5","font":{"size":30},"xaxis":{"titlefont":{"size":22},"tickfont":{"size":18}},"yaxis":{"titlefont":{"size":22},"tickfont":{"size":18}},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"labels":["Chocolate","Vainilla","Fresa"],"values":[103,92,72],"type":"pie","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(241,245,245,1)"}},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>¿Cuál de las dos formas es más apropiada?</p>
<div class="cell">
<div class="cell-output-display">
<div id="htmlwidget-db066ee7ce9e82f19a06" style="width:850px;height:600px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-db066ee7ce9e82f19a06">{"x":{"visdat":{"5c584fe124c9":["function () ","plotlyVisDat"]},"cur_data":"5c584fe124c9","attrs":{"5c584fe124c9":{"x":{},"y":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"width":850,"height":600,"margin":{"b":40,"l":60,"t":25,"r":10},"paper_bgcolor":"#F1F5F5","plot_bgcolor":"#F1F5F5","font":{"size":30},"xaxis":{"domain":[0,1],"automargin":true,"title":{"text":"Sabor","font":{"size":30}},"tickfont":{"size":25},"type":"category","categoryorder":"array","categoryarray":["Chocolate","Vainilla","Fresa"]},"yaxis":{"domain":[0,1],"automargin":true,"title":{"text":"Votos","font":{"size":30}},"tickfont":{"size":25}},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["Chocolate","Vainilla","Fresa"],"y":[103,92,72],"type":"bar","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>¡Importante!</h2>
<ul>
<li>Estos conocimientos se van a ir construyendo poco a poco.</li>
<li>Para <span class="hi">muestras</span> y <span class="hi">poblaciones</span> se usan notaciones diferentes.</li>
<li>Preste atención a lo largo de este y otros cursos, sobre todo de esta área de conocimiento, a las diferentes notaciones. Por ejemplo, la proporción muestral se denota con <span class="math inline">\(\hat{p}\)</span> mientras que la poblacional con <span class="math inline">\(p\)</span>. De la misma forma el promedio muestral es <span class="math inline">\(\bar{x}\)</span> y el poblacional es <span class="math inline">\(\mu\)</span>.</li>
<li>En este sentido, <span class="hi">recuerde</span> que hay una diferencia entre estimador y parámetro.</li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>Otro ejemplo</h2>
<ul>
<li>El Instituto Costarricense de Turismo (ICT) realiza encuestas para determinar los perfiles de los turistas que ingresan por distintas vías al país.
<ul>
<li><a href="https://www.ict.go.cr/es/estadisticas/encuestas.html" target="_blank">Enlace a Encuestas ICT</a></li>
</ul></li>
<li>Para las personas que ingresan vía aeropuerto se obtiene, entre otros, la variable: <u>Motivo del viaje</u>.
<ul>
<li>Discuta: ¿Por qué para un profesional de la ingeniería industrial estudiar esta variable puede ser importante?</li>
</ul></li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>Otro ejemplo</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>El ICT informa que la encuesta se realiza durante todo el año y de forma <span class="hi">aleatoria</span>. Consiguiendo la respuesta de 5 094 personas.
<ul>
<li>¿Cuál es la población?</li>
<li>¿Existe un sesgo evidente en la recolección de los datos?</li>
</ul></li>
</ul>
<p><img data-src="img/encuesta.png" width="250"></p>
</div><div class="column" style="font-size: 0.86em;">
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top" style="margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Motivo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Porcentaje</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Vacaciones</td>
<td style="text-align: right;">65.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Visita a familiares</td>
<td style="text-align: right;">9.60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Religión/peregrinaciones</td>
<td style="text-align: right;">6.40</td>
</tr>
<tr class="even">
<td style="text-align: left;">Educación</td>
<td style="text-align: right;">5.90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Salud</td>
<td style="text-align: right;">0.60</td>
</tr>
<tr class="even">
<td style="text-align: left;">Compras</td>
<td style="text-align: right;">0.30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Incentivo</td>
<td style="text-align: right;">0.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">Otros motivos personales</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Reuniones de negocios</td>
<td style="text-align: right;">8.07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conferencias y congresos</td>
<td style="text-align: right;">1.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Actividades deportivas/culturales</td>
<td style="text-align: right;">2.00</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Ejemplo - Visualización</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3>¿Qué opina de este gráfico?</h3>
<div class="cell">
<div class="cell-output-display">
<div id="htmlwidget-d33e93caa6fe2259ce19" style="width:850px;height:500px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-d33e93caa6fe2259ce19">{"x":{"visdat":{"5c587ecc1a29":["function () ","plotlyVisDat"]},"cur_data":"5c587ecc1a29","attrs":{"5c587ecc1a29":{"labels":{},"values":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"pie"}},"layout":{"width":850,"height":500,"margin":{"b":40,"l":60,"t":25,"r":10},"paper_bgcolor":"#F1F5F5","plot_bgcolor":"#F1F5F5","font":{"size":22},"xaxis":{"titlefont":{"size":22},"tickfont":{"size":18}},"yaxis":{"titlefont":{"size":22},"tickfont":{"size":18}},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"labels":["Vacaciones","Visita a familiares","Religión/peregrinaciones","Educación","Salud","Compras","Incentivo","Otros motivos personales","Reuniones de negocios","Conferencias y congresos","Actividades deportivas/culturales"],"values":[65.099999999999994,9.5999999999999996,6.4000000000000004,5.9000000000000004,0.59999999999999998,0.29999999999999999,0.040000000000000001,1,8.0700000000000003,1.0700000000000001,2],"type":"pie","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(241,245,245,1)"}},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div><div class="column" style="width:50%;">
<h3>¿Resulta más claro este?</h3>
<div class="cell">
<div class="cell-output-display">
<div id="htmlwidget-46db520a7258a2216ee1" style="width:850px;height:600px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-46db520a7258a2216ee1">{"x":{"visdat":{"5c581a345eb":["function () ","plotlyVisDat"]},"cur_data":"5c581a345eb","attrs":{"5c581a345eb":{"x":{},"y":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"width":850,"height":600,"margin":{"b":40,"l":60,"t":25,"r":10},"paper_bgcolor":"#F1F5F5","plot_bgcolor":"#F1F5F5","font":{"size":25},"xaxis":{"domain":[0,1],"automargin":true,"title":{"text":"Motivo","font":{"size":25}},"tickfont":{"size":20},"tickangle":30,"type":"category","categoryorder":"array","categoryarray":["Actividades deportivas/culturales","Compras","Conferencias y congresos","Educación","Incentivo","Otros motivos personales","Religión/peregrinaciones","Reuniones de negocios","Salud","Vacaciones","Visita a familiares"]},"yaxis":{"domain":[0,1],"automargin":true,"title":{"text":"Porcentaje","font":{"size":25}},"tickfont":{"size":20}},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["Vacaciones","Visita a familiares","Religión/peregrinaciones","Educación","Salud","Compras","Incentivo","Otros motivos personales","Reuniones de negocios","Conferencias y congresos","Actividades deportivas/culturales"],"y":[65.099999999999994,9.5999999999999996,6.4000000000000004,5.9000000000000004,0.59999999999999998,0.29999999999999999,0.040000000000000001,1,8.0700000000000003,1.0700000000000001,2],"type":"bar","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Ejemplo - Visualización</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3>¿Esta es mejor opción?</h3>
<div class="cell">
<div class="cell-output-display">
<div id="htmlwidget-fa957c5d1dcdf6e85b79" style="width:850px;height:600px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-fa957c5d1dcdf6e85b79">{"x":{"visdat":{"5c5833835fc7":["function () ","plotlyVisDat"]},"cur_data":"5c5833835fc7","attrs":{"5c5833835fc7":{"x":{},"y":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"width":850,"height":600,"margin":{"b":40,"l":60,"t":25,"r":10},"paper_bgcolor":"#F1F5F5","plot_bgcolor":"#F1F5F5","font":{"size":25},"xaxis":{"domain":[0,1],"automargin":true,"title":{"text":"Motivo","font":{"size":25}},"tickfont":{"size":20},"tickangle":-30,"type":"category","categoryorder":"array","categoryarray":["Vacaciones","Visita a familiares","Religión/peregrinaciones","Educación","Salud","Compras","Incentivo","Otros motivos personales","Reuniones de negocios","Conferencias y congresos","Actividades deportivas/culturales"]},"yaxis":{"domain":[0,1],"automargin":true,"title":{"text":"Porcentaje","font":{"size":25}},"tickfont":{"size":20}},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["Vacaciones","Visita a familiares","Religión/peregrinaciones","Educación","Salud","Compras","Incentivo","Otros motivos personales","Reuniones de negocios","Conferencias y congresos","Actividades deportivas/culturales"],"y":[65.099999999999994,9.5999999999999996,8.0700000000000003,6.4000000000000004,5.9000000000000004,2,1.0700000000000001,1,0.59999999999999998,0.29999999999999999,0.040000000000000001],"type":"bar","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>El ejercicio de visualización de datos es, en el fondo, un acto profundamente humano; pues toma algo “abstracto” como números, distribuciones, incertidumbres, entre otros y los transmite en algo con significado. En la comunicación visual la simplicidad es importante.</p>
<blockquote>
<p><span class="hi">La perfección se alcanza, no cuando no hay nada más que añadir, sino cuando no hay nada más que quitar</span> - <em>Antoine de Saint-Exupery</em></p>
</blockquote>
</div></div>
</section></section>
<section>
<section class="title-slide slide level1 center">
<h1>Medidas para <span class="hi">dos</span> variables <span class="hi">cualitativas</span></h1>

</section>
<section class="slide level2 bloques">
<h2>Tablas de contingencia</h2>
<ul>
<li><p>Son también conocidas como “tabla de doble entrada”.</p></li>
<li><p>Se usan para mostrar la <span class="hi">relación</span> que existe entre dos variables categóricas.</p>
<ul>
<li>Las tablas de contingencia, además de para describir datos, tienen muchas aplicaciones en <span class="hi">estadística inferencial</span>.</li>
</ul></li>
<li><p>Las categorías de una de las variables son las filas y las de la otra variable son las columnas. Los cruces son el conteo de lso casos en los que ocurren ambas variables simultáneamente.</p></li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>Ejemplo</h2>
<div class="columns">
<div class="column" style="font-size: 0.9em;">
<ul>
<li>Mediante una <span class="hi">encuesta</span> se obtiene información respecto a la siguiente pregunta:
<ul>
<li>¿Hay un verdadero amor para cada persona?</li>
</ul></li>
<li>Las respuestas obtenidas se organizan en una tabla de contingencia. Lo que facilita su representación.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top" style="margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Respuesta</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Hombre</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mujer</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A favor</td>
<td style="text-align: right;">372</td>
<td style="text-align: right;">363</td>
<td style="text-align: right;">735</td>
</tr>
<tr class="even">
<td style="text-align: left;">En contra</td>
<td style="text-align: right;">807</td>
<td style="text-align: right;">1005</td>
<td style="text-align: right;">1812</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No lo sé</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">78</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">1213</td>
<td style="text-align: right;">1412</td>
<td style="text-align: right;">2625</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="font-size: 0.8em;">
<h3>Práctica</h3>
<ul>
<li>¿Qué proporción de mujeres está de acuerdo?
<ul>
<li><span class="math inline">\(\frac{363}{1412}=0.26\)</span></li>
</ul></li>
<li>¿Qué proporción de las personas que están de acuerdo son mujeres?
<ul>
<li><span class="math inline">\(\frac{363}{735}=0.49\)</span></li>
</ul></li>
<li>¿Qué proporción de los hombres está de acuerdo?
<ul>
<li><span class="math inline">\(\frac{372}{1213}=0.31\)</span></li>
</ul></li>
<li>¿Es más probable que las mujeres o los hombres crean en el amor verdadero?
<ul>
<li>Hombres</li>
</ul></li>
<li>¿Qué proporción de las personas encuestadas son mujeres?
<ul>
<li><span class="math inline">\(\frac{1412}{2625}=0.54\)</span></li>
</ul></li>
</ul>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>¿Cómo visualizar dos categorías?</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3>Gráficos de barras</h3>
<div class="cell">
<div class="cell-output-display">
<div id="htmlwidget-48b186d778ec2bcc3727" style="width:850px;height:600px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-48b186d778ec2bcc3727">{"x":{"data":[{"orientation":"v","width":[0.44999999999999996,0.45000000000000018,0.45000000000000018],"base":[0,0,0],"x":[0.77500000000000002,1.7749999999999999,2.7749999999999999],"y":[372,807,34],"text":["Respuesta: A favor<br />Cantidad:  372<br />Género: Hombre","Respuesta: En contra<br />Cantidad:  807<br />Género: Hombre","Respuesta: No lo sé<br />Cantidad:   34<br />Género: Hombre"],"type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(228,26,28,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Hombre","legendgroup":"Hombre","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.45000000000000018,0.45000000000000018,0.45000000000000018],"base":[0,0,0],"x":[1.2250000000000001,2.2250000000000001,3.2250000000000001],"y":[363,1005,44],"text":["Respuesta: A favor<br />Cantidad:  363<br />Género: Mujer","Respuesta: En contra<br />Cantidad: 1005<br />Género: Mujer","Respuesta: No lo sé<br />Cantidad:   44<br />Género: Mujer"],"type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(55,126,184,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Mujer","legendgroup":"Mujer","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":26.350076103500765,"r":7.3059360730593621,"b":40.304414003044151,"l":48.949771689497723},"plot_bgcolor":"#F1F5F5","paper_bgcolor":"#F1F5F5","font":{"color":"rgba(0,0,0,1)","family":"","size":25},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.40000000000000002,3.6000000000000001],"tickmode":"array","ticktext":["A favor","En contra","No lo sé"],"tickvals":[1,2,3],"categoryorder":"array","categoryarray":["A favor","En contra","No lo sé"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":20},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"Respuesta","font":{"color":"rgba(0,0,0,1)","family":"","size":25}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-50.25,1055.25],"tickmode":"array","ticktext":["0","250","500","750","1000"],"tickvals":[0,250,500,750,1000],"categoryorder":"array","categoryarray":["0","250","500","750","1000"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":20},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"Cantidad","font":{"color":"rgba(0,0,0,1)","family":"","size":25}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176002,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":"#F1F5F5","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":20},"title":{"text":"Género","font":{"color":"rgba(0,0,0,1)","family":"","size":25}}},"hovermode":"closest","width":850,"height":600,"barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"5c5859ab67be":{"x":{},"y":{},"fill":{},"type":"bar"}},"cur_data":"5c5859ab67be","visdat":{"5c5859ab67be":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div><div class="column" style="width:50%;">
<h3>Gráficos de barras apiladas</h3>
<div class="cell">
<div class="cell-output-display">
<div id="htmlwidget-f7b9f2ddfbf203cb7b14" style="width:850px;height:600px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-f7b9f2ddfbf203cb7b14">{"x":{"data":[{"orientation":"v","width":[0.89999999999999991,0.90000000000000013,0.90000000000000036],"base":[0.49387755102040815,0.55463576158940397,0.5641025641025641],"x":[1,2,3],"y":[0.50612244897959191,0.44536423841059603,0.4358974358974359],"text":["Respuesta: A favor<br />Cantidad: 0.5061224<br />Género: Hombre","Respuesta: En contra<br />Cantidad: 0.4453642<br />Género: Hombre","Respuesta: No lo sé<br />Cantidad: 0.4358974<br />Género: Hombre"],"type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(228,26,28,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Hombre","legendgroup":"Hombre","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.89999999999999991,0.90000000000000013,0.90000000000000036],"base":[0,0,0],"x":[1,2,3],"y":[0.49387755102040815,0.55463576158940397,0.5641025641025641],"text":["Respuesta: A favor<br />Cantidad: 0.4938776<br />Género: Mujer","Respuesta: En contra<br />Cantidad: 0.5546358<br />Género: Mujer","Respuesta: No lo sé<br />Cantidad: 0.5641026<br />Género: Mujer"],"type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(55,126,184,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Mujer","legendgroup":"Mujer","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":26.350076103500765,"r":7.3059360730593621,"b":40.304414003044151,"l":48.949771689497723},"plot_bgcolor":"#F1F5F5","paper_bgcolor":"#F1F5F5","font":{"color":"rgba(0,0,0,1)","family":"","size":25},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.40000000000000002,3.6000000000000001],"tickmode":"array","ticktext":["A favor","En contra","No lo sé"],"tickvals":[1,2,3],"categoryorder":"array","categoryarray":["A favor","En contra","No lo sé"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":20},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"Respuesta","font":{"color":"rgba(0,0,0,1)","family":"","size":25}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-0.050000000000000003,1.05],"tickmode":"array","ticktext":["0.00","0.25","0.50","0.75","1.00"],"tickvals":[0,0.25,0.5,0.75,1],"categoryorder":"array","categoryarray":["0.00","0.25","0.50","0.75","1.00"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":20},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"Cantidad","font":{"color":"rgba(0,0,0,1)","family":"","size":25}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176002,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":"#F1F5F5","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":20},"title":{"text":"Género","font":{"color":"rgba(0,0,0,1)","family":"","size":25}}},"hovermode":"closest","width":850,"height":600,"barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"5c585c1b7944":{"x":{},"y":{},"fill":{},"type":"bar"}},"cur_data":"5c585c1b7944","visdat":{"5c585c1b7944":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div></div>
</section></section>
<section>
<section class="title-slide slide level1 center">
<h1>Medidas para <span class="hi">una o más</span> variables <span class="hi">cuantitativas</span></h1>

</section>
<section class="slide level2 bloques">
<h2>¿Cómo se describe una variable cuantitativa?</h2>
<ul>
<li>Hay tres formas de hacerlo:
<ul>
<li>Medidas de ubicación, posición o tendencia central</li>
<li>Medidas de dispersión</li>
<li>Medidas de forma</li>
</ul></li>
<li><svg aria-hidden="true" role="img" viewbox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zm0-384c13.3 0 24 10.7 24 24V264c0 13.3-10.7 24-24 24s-24-10.7-24-24V152c0-13.3 10.7-24 24-24zM224 352a32 32 0 1 1 64 0 32 32 0 1 1 -64 0z"></path></svg> <strong>Advertencia</strong>: Estas medidas también pueden usar para dos o más variables cuantitativas, categorizadas por variables cualitativas.
<ul>
<li>Por ejemplo: salario promedio por género.</li>
</ul></li>
</ul>
</section>
<section class="slide level2 bloques" style="font-size: 1.5em;">
<h2>Médidas de posición</h2>
<ul>
<li>Están diseñadas para brindar a la persona analista algunos <span class="hi">valores cuantitativos</span> de la ubicación central (u otros) de los datos en una población o en una muestra.</li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>1. Media o promedio</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Sirve como medida para expresar el centro de una distribución.</li>
<li>A modo de analogía, la media se puede interpretar como un “centro de gravedad”.</li>
<li>Esta es la <span class="hi">principal desventaja</span> de la media: <span class="hi">se ve MUY afectada por la presencia de valores extremos</span>.
<ul>
<li>No es una práctica ética eliminar valores extremos sin justificarlo y reportarlo.</li>
</ul></li>
</ul>
<p><img data-src="img/centro_gravedad.png" width="400"></p>
</div><div class="column" style="font-size: 0.92em;">
<h3>Por ejemplo</h3>
<ul>
<li>En una muestra, la media de 5 números <em>aproximadamente</em> similares: 4, 3, 5, 4 y 6 es <span class="math inline">\(\bar{x}=4.4\)</span>.
<ul>
<li>Esto sería como una regla <svg aria-hidden="true" role="img" viewbox="0 0 640 512" style="height:1em;width:1.25em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M0 336c0 26.5 21.5 48 48 48l544 0c26.5 0 48-21.5 48-48l0-160c0-26.5-21.5-48-48-48l-64 0 0 80c0 8.8-7.2 16-16 16s-16-7.2-16-16l0-80-64 0 0 80c0 8.8-7.2 16-16 16s-16-7.2-16-16l0-80-64 0 0 80c0 8.8-7.2 16-16 16s-16-7.2-16-16l0-80-64 0 0 80c0 8.8-7.2 16-16 16s-16-7.2-16-16l0-80-64 0 0 80c0 8.8-7.2 16-16 16s-16-7.2-16-16l0-80-64 0c-26.5 0-48 21.5-48 48L0 336z"></path></svg>, “<em>uniforme</em>” en toda la superficie, por lo que el centro de gravedad está en el “<em>centro</em>”.</li>
</ul></li>
<li>La media de 5 números con uno sumamente distinto (valor extremo): 2, 3, 5, 4 y 25 es <span class="math inline">\(\bar{x}=8.8\)</span>.
<ul>
<li>Esto sería como un martillo <svg aria-hidden="true" role="img" viewbox="0 0 576 512" style="height:1em;width:1.12em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M413.5 237.5c-28.2 4.8-58.2-3.6-80-25.4l-38.1-38.1C280.4 159 272 138.8 272 117.6V105.5L192.3 62c-5.3-2.9-8.6-8.6-8.3-14.7s3.9-11.5 9.5-14l47.2-21C259.1 4.2 279 0 299.2 0h18.1c36.7 0 72 14 98.7 39.1l44.6 42c24.2 22.8 33.2 55.7 26.6 86L503 183l8-8c9.4-9.4 24.6-9.4 33.9 0l24 24c9.4 9.4 9.4 24.6 0 33.9l-88 88c-9.4 9.4-24.6 9.4-33.9 0l-24-24c-9.4-9.4-9.4-24.6 0-33.9l8-8-17.5-17.5zM27.4 377.1L260.9 182.6c3.5 4.9 7.5 9.6 11.8 14l38.1 38.1c6 6 12.4 11.2 19.2 15.7L134.9 484.6c-14.5 17.4-36 27.4-58.6 27.4C34.1 512 0 477.8 0 435.7c0-22.6 10.1-44.1 27.4-58.6z"></path></svg>, cargado en un extremo.</li>
<li>También puede darse el caso de que haya valores extremos en ambas direcciones, comportándose como una mancuerna <svg aria-hidden="true" role="img" viewbox="0 0 640 512" style="height:1em;width:1.25em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M96 64c0-17.7 14.3-32 32-32h32c17.7 0 32 14.3 32 32V224v64V448c0 17.7-14.3 32-32 32H128c-17.7 0-32-14.3-32-32V384H64c-17.7 0-32-14.3-32-32V288c-17.7 0-32-14.3-32-32s14.3-32 32-32V160c0-17.7 14.3-32 32-32H96V64zm448 0v64h32c17.7 0 32 14.3 32 32v64c17.7 0 32 14.3 32 32s-14.3 32-32 32v64c0 17.7-14.3 32-32 32H544v64c0 17.7-14.3 32-32 32H480c-17.7 0-32-14.3-32-32V288 224 64c0-17.7 14.3-32 32-32h32c17.7 0 32 14.3 32 32zM416 224v64H224V224H416z"></path></svg>.
<ul>
<li>Por ejemplo: 2, 9, 12, 8, 11, 35 tiene como media <span class="math inline">\(\bar{x}=12.83\)</span></li>
</ul></li>
</ul></li>
</ul>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>1. Media o promedio - Fórmulas</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3>Poblacional</h3>
<p><span class="math display">\[
\mu=\frac{\sum_{i=1}^N x_i}{N}
\]</span></p>
<ul>
<li><p>Siendo <span class="math inline">\(\mu\)</span> el promedio, <span class="math inline">\(x_i\)</span> los valores individuales y <span class="math inline">\(N\)</span> la cantidad de datos en la población.</p></li>
<li><p>En este sentido <span class="math inline">\(\mu\)</span> es un parámetro y <span class="math inline">\(\bar{x}\)</span> es un estimador.</p></li>
</ul>
</div><div class="column" style="width:50%;">
<h3>Muestral</h3>
<ul>
<li>Note el cambio en la notación (los símbolos). La notación es muy importante para esta área de conocimiento.</li>
</ul>
<p><span class="math display">\[
\bar{x}=\frac{\sum_{i=1}^n x_i}{n}
\]</span></p>
<ul>
<li>Siendo <span class="math inline">\(\bar{x}\)</span> el promedio, <span class="math inline">\(x_i\)</span> los valores individuales y <span class="math inline">\(n\)</span> la cantidad de datos en la muestra.</li>
</ul>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Media geométrica y armónica</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3>1.2 Geométrica (G)</h3>
<ul>
<li>Es un tipo de media que se calcula como la raíz n-esima del producto de un conjunto de número estrictamente positivos</li>
<li>Se suele usar para calcular medias sobre porcentajes. Es menos sensible a datos extremos.</li>
</ul>
<p><span class="math display">\[\bar{x}_G=(x_1 \cdot x_2 \cdots x_n)^\frac{1}{n}\]</span></p>
</div><div class="column" style="width:50%;">
<h3>1.3 Armónica (H)</h3>
<ul>
<li>Es un tipo de media que es igual al número de elementos de un grupo de cifras entre la suma de los inversos de cada una de esas cifras.</li>
<li>Se suele usar con velocidades, tiempos, entre otros. También es menos sensible a datos extremos y solo funciona en números positivos.</li>
</ul>
<p><span class="math display">\[
\bar{x}_H=\frac{n}{\frac{1}{x_1} + \frac{1}{x_2} + \cdots +\frac{1}{x_n}}
\]</span></p>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>1.4 Media ponderada</h2>
<div class="columns">
<div class="column">
<ul>
<li>Constituye un caso especial de la media, se presenta cuando hay varias observaciones con el mismo valor.</li>
<li>Suponga que en Hangar se venden 3 tipos de café: pequeño, mediano y grande. En un momento particular se venden 3 pequeños, 2 medianos y 3 grandes. ¿Cuál es el promedio de las ventas?
<ul>
<li>Note que es igual a como se calcula el promedio ponderado de matrícula</li>
</ul></li>
</ul>
</div><div class="column">
<h3>Muestral</h3>
<ul>
<li><span class="math display">\[\bar{x}=\frac{\sum_{i=1}^n w_i\cdot x_i}{\sum_{i=1}^n w_i}\]</span></li>
</ul>
<h3>Poblacional</h3>
<ul>
<li><span class="math display">\[\bar{x}=\frac{\sum_{i=1}^N w_i\cdot x_i}{\sum_{i=1}^N w_i}\]</span></li>
</ul>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Media ponderada - Ejemplo</h2>
<div class="columns">
<div class="column" style="width:100%;">
<ul>
<li>Resolviendo las ecuaciones:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top" style="margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Presentación</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Ventas</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Precio</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Promedio de ventas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Pequeño</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">1500</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mediano</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">700</td>
<td style="text-align: right;">1400</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Grande</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">900</td>
<td style="text-align: right;">2700</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">2100</td>
<td style="text-align: right;">5600</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>Se obtiene un promedio ponderado de <span class="math inline">\(\bar{x}_w=\frac{5600}{8}=700\)</span> colones.</li>
</ul>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>1.5 Media recortada</h2>
<ul>
<li>Como se ha enfatizado, la <span class="hi">media es bastante sensible</span> a un solo valor extremo.</li>
<li>La media recortada se calcula “quitando” cierto porcentaje de los valores mayores y menores del conjunto de datos.
<ul>
<li>Se eliminan <span class="math inline">\(k\)</span> valores de ambos extremos, no solo de uno.</li>
<li><span class="math inline">\(\bar{x}_{\text{rec}} = \frac{1}{n - 2k} \sum_{i = k+1}^{n-k} x_{(i)}\)</span></li>
</ul></li>
<li>Por ejemplo, una media recortada al 10 % se calcula eliminando tanto el 10 % de los valores menores como el 10 % de los valores mayores. Y se calcula el promedio de los valores “sobrevivientes”.
<ul>
<li>Si se tienen 7 datos y se elige un recorte de 10 %, <span class="math inline">\(k=7\cdot 0.1=0.7=0\)</span> la media recortada sería igual a la media, pues no se eliminarían datos, si se elige 20 %, <span class="math inline">\(k=7\cdot 0.2=1.4=1\)</span> se eliminaría 1 dato en cada extremo (el menor y el mayor).</li>
</ul></li>
</ul>
</section>
<section class="slide level2 bloques" style="font-size: 1.2em;">
<h2>2. Mediana</h2>
<ul>
<li>Sirve también como medida para expresar el centro de una distribución. <span class="hi">No se ve afectada significativamente por valores extremos</span>.</li>
<li>Cuando el conjunto de datos contiene uno o dos valores muy grandes o muy pequeños la media <span class="hi">NO RESULTA REPRESENTATIVA</span>.
<ul>
<li>Es en estos casos en los que la <span class="hi">mediana</span> es usada para describir el centro de los datos.</li>
</ul></li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>Ejemplo</h2>
<div class="columns">
<div class="column img-fit" style="width:60%;">
<p><img data-src="img/Infografía Radiografía Laboral 2022 Ingeniería Industrial.png"></p>
</div><div class="column" style="width:40%;">
<p>¿Alguna vez se preguntó por el salario en su carrera?</p>
<p>La gran mayoría de estudios responden al salario promedio. Inlcusive, muchos de ustedes durante las ferias vocacionales realizan esta pregunta.</p>
<p><span class="hi">¿Eso está bien?</span> La respuesta es ¡no! los salarios siempre tienen valores extremos.</p>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>El problema del promedio vs la mediana</h2>
<div class="columns">
<div class="column" style="font-size: 1.1em;">
<ul>
<li>Por esto es importante, en algunos conjuntos de datos, estimar la mediana en lugar de la media.
<ul>
<li>OJO: esto no es una “receta”, cada contexto se analiza en consecuencia.</li>
</ul></li>
<li>Entonces, <span class="hi">¿El salario promedio es adecuado?</span></li>
</ul>
</div><div class="column img-fit" style="width:40%;">
<video id="video_shortcode_videojs_video1" height="710" class="video-js vjs-default-skin " controls="" preload="auto" data-setup="{}" title=""><source src="img/salario_promedio.mp4"></video>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>2. Mediana - Fórmulas</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3>Poblacional</h3>
<p>Es literalmente el valor medio de un conjunto de <span class="hi">datos ordenados</span> de menor a mayor.</p>
<p><span class="math display">\[
\widetilde{X} = \begin{cases} x_{\frac{N+1}{2}} &amp; \text{si N es impar} \\ \frac{1}{2} \cdot (x_{\frac{N}{2}}+x_{\frac{N}{2}+1}) &amp; \text{si N es par} \end{cases}
\]</span></p>
<ul>
<li><p>Siendo <span class="math inline">\(\tilde{x}\)</span> la mediana.</p></li>
<li><p>En este sentido <span class="math inline">\(\widetilde{X}\)</span> es un parámetro y <span class="math inline">\(\tilde{x}\)</span> es un estimador.</p></li>
</ul>
</div><div class="column" style="width:50%;">
<h3>Muestral</h3>
<p><span class="math display">\[
\tilde{x} = \begin{cases} x_{\frac{n+1}{2}} &amp; \text{si n es impar} \\ \frac{1}{2} \cdot (x_{\frac{n}{2}}+x_{\frac{n}{2}+1}) &amp; \text{si n es par} \end{cases}
\]</span></p>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Ejemplo</h2>
<div class="columns">
<div class="column" style="width:65%;">
<p>Por ejemplo, en estos valores ordenados:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top" style="margin-left: auto; margin-right: auto;">
<tbody>
<tr class="odd">
<td style="text-align: left;">valores</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">52</td>
</tr>
<tr class="even">
<td style="text-align: left;">Posición</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La mediana es:</p>
<p><span class="math display">\[\tilde{x}=\frac{1}{2} \cdot (x_{\frac{10}{2}}+x_{\frac{10}{2}+1}) \\ \tilde{x} =\frac{1}{2}\cdot (39 + 40) \\ \tilde{x} =39.5\]</span></p>
</div><div class="column img-fit" style="width:35%;">
<p><img data-src="img\example.gif"></p>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>3. Moda</h2>
<ul>
<li><p>Es el valor del conjunto de datos que aparece con mayor frecuencia. Al igual que con la mediana y a diferencia de la media, los valores extremos no afectan a la moda.</p></li>
<li><p>La moda <span class="hi">solo se usa con propósitos descriptivos</span> (es decir, no para hacer inferencias), ya que varía más entre muestras que la media o la mediana.</p></li>
<li><p>En simple, es el valor que más repite en una distribución de datos. Como tal no tiene fórmula, pues se trata de un simple conteo.</p></li>
<li><blockquote>
<p>Es posible que haya conjuntos de datos sin moda o con varias modas.</p>
</blockquote></li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>4. Cuantiles</h2>
<ul>
<li>Dividen el conjunto de datos en partes iguales. El procedimiento manual siempre inicia con ordenar los datos de menor a mayor (<em>en este sentido se sigue la misma lógica de cálculo que en la mediana, pues esta es un caso de los cuantiles</em>). Y tomar decisiones si la cantidad de datos es par o impar.
<ul>
<li><strong>Percentil</strong> (P): divide a los datos en 100 partes iguales</li>
<li><strong>Quintil</strong>: divide a los datos en 5 partes iguales</li>
<li><strong>Cuartil</strong> (Q): divide a los datos en 4 partes iguales</li>
<li><strong>Mediana</strong>: divide a los datos en 2 partes iguales El <span class="math inline">\(P_50\)</span> es igual al <span class="math inline">\(Q_2\)</span> que es igual a la mediana (<span class="math inline">\(\tilde{x}\)</span>).</li>
</ul></li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>¿Cómo se interpretan?</h2>
<div class="columns">
<div class="column" style="font-size: 1.2em;">
<ul>
<li>Por ejemplo, para el siguiente conjunto de datos el <span class="math inline">\(Q_1\)</span> es 35
<ul>
<li>29, 31, 35, 39, 40, 43, 44, 44, 52
<ul>
<li>En Excel usamos <code>QUARTILE.INC</code> en lugar de <code>QUARTILE.EXC</code>, si se usa <code>QUARTILE.EXC</code> el resultado sería 33 y no 35. La función <code>QUARTILE.EXC</code> excluye valores extremos del conjunto de datos.</li>
</ul></li>
</ul></li>
<li><span class="hi">Interpretación</span>:
<ul>
<li>El 25 % de los datos se encuentran por debajo de 35.</li>
</ul></li>
<li>Calcule e interprete otros cuantiles.</li>
</ul>
</div><div class="column" style="width:40%;">
<h3>Algunas equivalencias</h3>
<ul>
<li><span class="math inline">\(P_{25}=Q_1\)</span></li>
<li><span class="math inline">\(P_{50}=Q_2=\tilde{x}\)</span></li>
<li><span class="math inline">\(P_{75}=Q_3\)</span></li>
<li><span class="math inline">\(P_{20}=Quintil_1\)</span></li>
<li><span class="math inline">\(P_{40}=Quintil_2\)</span></li>
<li><span class="math inline">\(P_{60}=Quintil_3\)</span></li>
<li><span class="math inline">\(P_{80}=Quintil_4\)</span></li>
</ul>
</div></div>
</section>
<section class="slide level2 bloques" style="font-size: 1.1em;">
<h2>Médidas de dispersión o variabilidad</h2>
<ul>
<li><p>La variabilidad de una muestra desempeña un papel importante en el análisis de datos. La <span class="hi">variabilidad de procesos y productos es un hecho real en los sistemas científicos y de ingeniería</span>: el control o la reducción de la variabilidad de un proceso a menudo es una fuente de mayores dificultades.</p></li>
<li><p>Las medidas de tendencia central o posición <span class="hi">siempre</span> deben acompañarse de medidas de <span class="hi">variablidad</span>.</p></li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>Rangos</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3>1. Rango</h3>
<ul>
<li><p>Son las medidas de variabilidad más simples.</p></li>
<li><p>El defecto o desventaja de los rangos es que depende únicamente de dos valores, y por ende es <span class="hi">sensible</span> a si estos son extremos en comparación al resto del conjunto de datos.</p></li>
<li><p>Se refiere a la diferencia entre el valor máximo y el mínimo.</p></li>
</ul>
<p><span class="math display">\[
R=Máx-Min
\]</span></p>
</div><div class="column" style="width:50%;">
<h3>2. Rango Intercuartil (RIC o <em>IQR</em>)</h3>
<ul>
<li>Esta reduce el riesgo de la anterior, pues es una medida de dispersión del 50 % central de los datos.</li>
</ul>
<p><span class="math display">\[
IQR = Q_3-Q_1 \\ IQR = P_{75}-P_{25}
\]</span></p>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>3. Varianza y desviación estándar</h2>
<ul>
<li>Es una medida que indica la <span class="hi">desviación</span> que tienen los datos alrededor de la <strong>media</strong> (mucha atención a la fórmula).
<ul>
<li>Una varianza (desviación) “alta” indica que los datos se encuentran muy dispersos, por el contrario una baja indicaría que los datos se encuentran poco dispersos alrededor de la media.</li>
</ul></li>
<li>Lo correcto es siempre analizar las medidas de posición, acompañadas de medidas de variabilidad.
<ul>
<li>¿Por qué? Discuta con la persona docente y otras personas estudiantes.</li>
</ul></li>
<li>Se suele usar la desviación estándar en lugar de la varianza, porque la segunda tiene una interpretación “más complicada”.</li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>3. Varianza y desviación estándar</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3>Poblacional</h3>
<ul>
<li>Varianza</li>
</ul>
<p><span class="math display">\[
\sigma^2=\frac{\sum_{i=1}^{N}(\bar{x}-\mu)^2}{N}
\]</span></p>
<ul>
<li>Desviación estándar</li>
</ul>
<p><span class="math display">\[
\sigma=\sqrt{\frac{\sum_{i=1}^{N}(\bar{x}-\mu)^2}{N}}
\]</span></p>
</div><div class="column" style="width:50%;">
<h3>Muestral</h3>
<ul>
<li>Varianza</li>
</ul>
<p><span class="math display">\[
s^2=\frac{\sum_{i=1}^{N}(\bar{x}-\mu)^2}{n-1}
\]</span></p>
<ul>
<li>Desviación estándar</li>
</ul>
<p><span class="math display">\[
s=\sqrt{\frac{\sum_{i=1}^{N}(\bar{x}-\mu)^2}{n-1}}
\]</span></p>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>¿Por qué n-1?</h2>
<ul>
<li><p>Se llama la corrección de Bessel</p></li>
<li><p>Justificación por intuición:</p>
<ul>
<li>Básicamente 𝑛−1 provee una estimación insesgada del estimador de la varianza poblacional. El <span class="math inline">\(n-1\)</span> implica que un grado de libertad se pierde (en realidad se usa) para estimar la media muestral <span class="math inline">\(\bar{x}\)</span>.</li>
</ul></li>
<li><p>Los grados de libertad (tema que se detalla en otras sesiones) son las piezas de información que se utilizan para calcular un estimador, en este caso 1 grado de libertad se usó para calcular la media (<span class="math inline">\(\bar{x}\)</span>), por lo que solo quedarían <span class="math inline">\(n-1\)</span> para la varianza.</p></li>
<li><p>La justificación por demostración está disponible en este <a href="https://stevenggoni.github.io/interactivos/demostracion_n-1.html" target="_blank">sitio web</a> como material <strong>complementario</strong> y <strong>opcional</strong>.</p></li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>4. Coeficiente de variación (CV)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Es una medida de dispersión relativa de un determinado conjunto de datos.
<ul>
<li>¿Relativo a quién? A la <span class="hi">media</span>.</li>
<li>Observemos la fórmula.</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<h3>Poblacional</h3>
<p><span class="math display">\[
CV = \frac{\sigma}{\mu}
\]</span></p>
<h3>Muestral</h3>
<p><span class="math display">\[
\widehat{CV} = \frac{s}{\bar{x}}
\]</span></p>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>4. Coeficiente de variación (CV)</h2>
<ul>
<li>¿Cuándo deberíamos usar el CV y no la desviación estándar o la varianza?</li>
<li>Note de la fórmula que el CV es <span class="hi">adimensional</span>, eso nos permite comparar la variabilidad de variables con <span class="hi">diferentes unidades</span>.</li>
<li>Su interpretación se puede expresar como porcentaje.</li>
<li>Por ejemplo:
<ul>
<li>¿Qué es más variable, el peso o la edad de una persona?</li>
</ul></li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>Resumen</h2>
<ul>
<li>En términos generales <span class="hi">es siempre conveniente presentar las medidas de posición acompañadas de medidas de dispersión</span>.</li>
<li>Pues complementan la información dada por las medidas de tendencia central (posición). * Hace posible la comparación entre diferentes grupos.
<ul>
<li>Sirven como control para evitar conclusiones erróneas en la comparación de datos.</li>
</ul></li>
<li>¿Cuál medida de dispersión es la más adecuada para las respectivas medidas de posición?</li>
<li>Para la <span class="hi">media</span> se suele usar la <span class="hi">desviación estándar</span>, mientras que para la <span class="hi">mediana</span> se sugiere usar alguna de las medidas de rango, preferiblemente el <span class="hi">IQR</span>.</li>
</ul>
</section>
<section class="slide level2 bloques" style="font-size: 1.2em;">
<h2>Médidas de dispersión o variabilidad</h2>
<ul>
<li><p>Describen la forma de una distribución de datos. Permiten identificar si una distribución es simétrica o asimétrica, o qué tan agrupados están los datos.</p></li>
<li><p>Son, probablemente, las medidas que típicamente se interpretan mal.</p></li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>1. Asimetría</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><p>Mide el grado de deformación horizontal en un conjunto de datos.</p></li>
<li><p>Hay muchos coeficientes de asimetría, todos se interpretan igual, pero se calculan de formas diversas.</p></li>
<li><p>Para efectos de este curso vamos a usar el coeficiente de asimetría que se encuentra disponible en Excel.</p></li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li><span class="math inline">\(Sk= \frac{n}{(n-1)(n-2)}\left[\sum_{i=1}^{n}\left(\frac{x_i-\bar{x}}{s}\right)^3\right]\)</span>
<ul>
<li><span class="math inline">\(Sk&lt;0\)</span>: asimetría postiva</li>
<li><span class="math inline">\(Sk=0\)</span>: distribución simétrica</li>
<li><span class="math inline">\(Sk&gt;0\)</span>: asimetría positiva</li>
</ul></li>
</ul>
<p><img data-src="img/asimetria.png" width="350"></p>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>1. Asimetría</h2>
<ul>
<li><p>Si la distribución de los datos es simétrica, la media, la mediana y la moda son coincidentes (iguales o muy similares).</p></li>
<li><p>Esta medida es importante ya que dos conjuntos de datos pueden tener la misma media y desviación estándar pero un diferente grado de asimetría.</p></li>
<li><p>Es común que en libros de texto en <strong>español</strong> y otras personas docentes utilicen el término <span class="hi">sesgo</span> como sinónimo de asimetría. De la clase anterior, sabemos que esto no es así.</p>
<ul>
<li><strong>Sesgo</strong>: Cuando el método de recopilación de datos hace que los datos de la muestra reflejen incorrectamente la población.</li>
</ul></li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>1. Asimetría</h2>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li>Una distribución puede ser asimétrica y no presentar ningún tipo de sesgo. O viceversa.</li>
<li>Los términos <span class="hi">NO SON intercambiables</span>. Use la terminología correcta.</li>
</ul>
<h3>¿De dónde proviene esto?</h3>
<ul>
<li>Básicamente, de un “error de traducción”. Para sesgo el término en inglés es bias, mientras que para asimetría es skewness.</li>
</ul>
</div><div class="column img-fit" style="width:30%;">
<p><img data-src="img/cero_sesgo.png"></p>
</div><div class="column img-fit" style="width:30%;">
<p><img data-src="img/zero_skewness.png"></p>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>2. Curtósis</h2>
<ul>
<li><p>Se define técnicamente como el cuarto momento estandarizado esperado de una variable aleatoria</p></li>
<li><p>Mide la concentración relativa de los valores en el centro de la distribución al compararlos con las colas y se basa en las diferencias respecto a la media elevadas a la cuarta potencia.</p></li>
<li><p>La interpretación de la curtosis es en términos de la extremidad de las colas; es decir, mide la propensión de una distribución a producir valores atípicos (<em>outliers</em>), y no la “puntiagudez” (<em>peakedness</em>) o forma del pico central.</p></li>
<li><p>A veces se confunde con cuan escarpada, achatada, etc, se encuentra una distribución de datos.</p></li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>2. Curtósis</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li><p>Usamos la misma fórmula que MS Excel:</p>
<ul>
<li>Esta fórmula mide el <u>exceso de curtosis</u>, es decir, que tan distinta es de una distribución normal (tema que se aborda adelante en el curso).</li>
</ul></li>
<li><p><span class="math inline">\(ku=\left[ \left(\frac{n(n+1)}{(n-1)(n-2)(n-3)}\sum_{i=1}^{n} \left(\frac{x_i-\bar{x}}{s}\right)^4 \right) \right] - \frac{3(n-1)}{(n-2)(n-3)}\)</span></p>
<ul>
<li><span class="math inline">\(ku&lt;0\)</span> platicúrtica:
<ul>
<li>Donde la curtosis es menor que la de la distribución normal</li>
</ul></li>
<li><span class="math inline">\(ku=0\)</span> mesocúrtica:
<ul>
<li>Donde la curtosis es igual a la de la distribución normal</li>
</ul></li>
<li><span class="math inline">\(ku&gt;0\)</span> leptocúrtica:
<ul>
<li>Donde la curtosis es mayor que la de la distribución normal</li>
</ul></li>
</ul></li>
</ul>
</div><div class="column img-fit" style="width:30%;">
<p><img data-src="img\curtosis.png"></p>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Presentación y visualización de datos</h2>
<ul>
<li>Recordemos que entre las funciones de la estadística descriptiva se encuentra el resumir datos.</li>
<li>El objetivo fundamental de agrupar los datos es que el análisis de los mismos pueda ser más sencillo, de manera que se pueda hacer una primera aproximación a los resultados de forma rápida.</li>
<li>La agrupación sirve para poder elaborar, a partir de la información recopilada, herramientas visuales como un histograma, un gráfico de barras o un gráfico circular.</li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>Presentación y visualización de datos</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3>Datos agrupados</h3>
<ul>
<li>Son aquellos que luego de ser recopilados se dividen y agrupan por categorías o intervalos.</li>
<li>¿Cómo se agrupan los datos? Para una sola variable se pueden usar tablas de frecuencia.</li>
</ul>
</div><div class="column" style="font-size: 0.83em;">
<h3>Tablas de frecuencia</h3>
<p>No existe una “regla” establecida para construir tablas de frecuencia. Pero debe asegurarse que los intervalos establecidos cubran todo el conjunto de datos.</p>
<ol type="1">
<li>Determinar la cantidad de datos (<span class="math inline">\(n\)</span>)</li>
<li>Escoger la regla de agrupación</li>
<li>Obtener la medida de variabilidad asociada a la regla de agrupación (<span class="math inline">\(R\)</span>, <span class="math inline">\(IQR\)</span>, <span class="math inline">\(s\)</span>)</li>
<li>Definir la cantidad de clases empleando la regla de agrupación.</li>
</ol>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Tablas de frecuencia</h2>
<div class="columns">
<div class="column" style="font-size: 0.83em;">
<h3>Reglas de agrupación</h3>
<ul>
<li>Sturges (<span class="math inline">\(n&lt;200\)</span>)</li>
</ul>
<p><span class="math display">\[
k=1+log_2(n)
\]</span></p>
<ul>
<li>Scott (<span class="math inline">\(n&gt;200\)</span>)</li>
</ul>
<p><span class="math display">\[
A_S=h=\frac{7\cdot s}{2\cdot \sqrt[3]{n}
}
\]</span></p>
<ul>
<li>Freedman-Diaconis</li>
</ul>
<p><span class="math display">\[
A_{FD}=h=\frac{2\cdot IQR}{\sqrt[3]{n}}
\]</span></p>
</div><div class="column" style="width:50%;">
<p>Si se definió <span class="math inline">\(k\)</span>, calcule <span class="math inline">\(h\)</span>, por el contrario, si definió <span class="math inline">\(h\)</span>, calcule <span class="math inline">\(k\)</span>.</p>
<p><span class="math display">\[
k= \frac{Rango}{h} \\k=\frac{max-min}{h}
\]</span></p>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Convencionalismo de redondeo para <span class="math inline">\(k\)</span></h2>
<ul>
<li><span class="math inline">\(k\)</span> es la cantidad de clases y como tal es siempre un número entero positivo.</li>
<li>Si el entero del resultado previo al redondeo es “<em>par</em>” se redondea a la alta y si el entero es “<em>impar</em>” se redondea a la baja, resultando siempre un número impar de clases.
<ul>
<li>6.26 redondea a 7.0</li>
<li>7.02 redondea a 7.0</li>
</ul></li>
<li>Las comillas en “regla” son importantes, pues esta no es inamovible. Es un convencionalismo.</li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>Ejemplo</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Tomemos el siguiente conjunto de datos, que por conveniencia ya viene ordenado.</p>
<p>Usemos la regla de Sturges y calculemos <span class="math inline">\(k\)</span></p>
<p><span class="math display">\[
k=1+log_2(12)=4.58=5
\]</span> Entonces:</p>
<p><span class="math display">\[
h=\frac{77.2-73.8}{5}=0.68
\]</span></p>
</div><div class="column" style="font-size: 0.8em;">
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top" style="margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Datos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">73.8</td>
</tr>
<tr class="even">
<td style="text-align: right;">74.2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">75.1</td>
</tr>
<tr class="even">
<td style="text-align: right;">75.3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">75.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">75.7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">76.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">76.9</td>
</tr>
<tr class="odd">
<td style="text-align: right;">77.1</td>
</tr>
<tr class="even">
<td style="text-align: right;">77.2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">77.2</td>
</tr>
<tr class="even">
<td style="text-align: right;">77.2</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>¿Cómo se construye una tabla de frecuencias?</h2>
<div class="columns">
<div class="column" style="width:100%;">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Clases</th>
<th>LI</th>
<th>LS</th>
<th><span class="math inline">\(f_a\)</span></th>
<th><span class="math inline">\(f_r\)</span></th>
<th><span class="math inline">\(F_a\)</span></th>
<th><span class="math inline">\(F_r\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><span class="math inline">\([Min\)</span></td>
<td><span class="math inline">\(LI_1 + h[\)</span></td>
<td>Conteo</td>
<td><span class="math inline">\(\frac{f_{a1}}{n}\)</span></td>
<td><span class="math inline">\(f_{a1}\)</span></td>
<td><span class="math inline">\(\frac{F_{a1}}{n}\)</span></td>
</tr>
<tr class="even">
<td>2</td>
<td><span class="math inline">\([LS_1\)</span></td>
<td><span class="math inline">\(LI_2 + h[\)</span></td>
<td>…</td>
<td><span class="math inline">\(\frac{f_{a2}}{n}\)</span></td>
<td><span class="math inline">\(f_{a1}+f_{a2}\)</span></td>
<td>…</td>
</tr>
<tr class="odd">
<td>3</td>
<td><span class="math inline">\([LS_2\)</span></td>
<td><span class="math inline">\(LI_3 + h[\)</span></td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="even">
<td>4</td>
<td>[…]</td>
<td>…[</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>5</td>
<td>[…]</td>
<td><span class="math inline">\(Max]\)</span></td>
<td>…</td>
<td>…</td>
<td><span class="math inline">\(f_{a1}+f_{a2}+…+f_{a5}=n\)</span></td>
<td><span class="math inline">\(\frac{F_{a5}}{n}=1\)</span></td>
</tr>
</tbody>
</table>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Ejemplo</h2>
<div class="columns">
<div class="column" style="width:100%;">
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top" style="margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Clase</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">fr</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Fa</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Fr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">[73.8,74.5]</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.167</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.167</td>
</tr>
<tr class="even">
<td style="text-align: left;">(74.5,75.2]</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.083</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.250</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(75.2,75.8]</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.500</td>
</tr>
<tr class="even">
<td style="text-align: left;">(75.8,76.5]</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.083</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.583</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(76.5,77.2]</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.417</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Histogramas</h2>
<div class="columns">
<div class="column" style="width:70%;">
<p>Los histogramas ayudan a dar una estimación de <span class="hi">dónde se concentran los valores, cuáles son los extremos y si hay vacíos o valores inusuales</span>.</p>
<p>También son útiles para dar una visión aproximada de la distribución de probabilidad.</p>
<p>Cada barra en un histograma representa la frecuencia tabulada en cada intervalo/bin. El área total del histograma es igual al número de datos.</p>
</div><div class="column img-fit" style="width:30%;">
<p><img data-src="img/histograma.svg"></p>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Ejemplo - Histograma</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div id="htmlwidget-1280492a4e9d58743a35" style="width:850px;height:600px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-1280492a4e9d58743a35">{"x":{"data":[{"orientation":"v","width":[0.84999999999999432,0.85000000000002274,0.85000000000002274,0.84999999999999432,0.84999999999999432],"base":[0,0,0,0,0],"x":[73.950000000000117,74.800000000000125,75.650000000000119,76.500000000000128,77.350000000000122],"y":[2,1,3,2,4],"text":["count: 2<br />Datos: 73.95","count: 1<br />Datos: 74.80","count: 3<br />Datos: 75.65","count: 2<br />Datos: 76.50","count: 4<br />Datos: 77.35"],"type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(139,0,0,1)","line":{"width":1.8897637795275593,"color":"rgba(255,255,255,1)"}},"showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":26.350076103500765,"r":7.3059360730593621,"b":40.304414003044151,"l":31.415525114155255},"plot_bgcolor":"#F1F5F5","paper_bgcolor":"#F1F5F5","font":{"color":"rgba(0,0,0,1)","family":"","size":25},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[73.312500000000114,77.987500000000125],"tickmode":"array","ticktext":["74","75","76","77"],"tickvals":[74,75,76,77],"categoryorder":"array","categoryarray":["74","75","76","77"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":20},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"Intervalos","font":{"color":"rgba(0,0,0,1)","family":"","size":25}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-0.20000000000000001,4.2000000000000002],"tickmode":"array","ticktext":["0","1","2","3","4"],"tickvals":[0,1,2,3,4],"categoryorder":"array","categoryarray":["0","1","2","3","4"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":20},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"Frecuencia","font":{"color":"rgba(0,0,0,1)","family":"","size":25}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176002,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"#F1F5F5","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":20},"title":{"font":{"size":25}}},"hovermode":"closest","width":850,"height":600,"barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"5c58681a70c":{"x":{},"type":"bar"}},"cur_data":"5c58681a70c","visdat":{"5c58681a70c":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>Un histograma es una forma de representación visual donde con una sola mirada la persona analista puede darse una idea de:
<ul>
<li>La ubicación de la media, mediana y moda</li>
<li>La curtosis y asimetría</li>
<li>La variabilidad de los datos</li>
</ul></li>
</ul>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Gráfico de cajas y bigotes</h2>
<ul>
<li>También conocido como boxplot.</li>
<li>Es una manera conveniente de mostrar visualmente grupos de datos numéricos a través de sus cuartiles.</li>
<li>Normalmente utilizado en estadísticas descriptivas, los gráficos de cajas y bigotes son una excelente forma de examinar rápidamente uno o más conjuntos de datos gráficamente.</li>
<li>En ocasiones al boxplot se le agrega un punto (u otro símbolo) representando la media o promedio.</li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>Valores atípicos</h2>
<div class="columns">
<div class="column" style="width:100%;">
<ul>
<li>Son valores dentro del conjunto de datos que difieren de forma “considerable” de los otros valores.</li>
<li><span class="hi">Importante</span>: los datos atípicos se estudian, pero NO se eliminan sin justificación válida.</li>
<li>Los gráficos de cajas y bigotes son una herramienta visual para la detección de datos “atípicos”.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/boxplot_montgomery.png" class="quarto-figure quarto-figure-center" width="800"></p>
</figure>
</div>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Gráficos de cajas y bigotes</h2>
<div class="columns">
<div class="column img-fit" style="width:30%;">
<p><img data-src="img/boxplot_espanol.svg"></p>
</div><div class="column" style="width:70%;">
<ul>
<li>Extremo superior
<ul>
<li>Es el valor extremo superior más pequeño que se encuentre dentro de:
<ul>
<li><span class="math inline">\(LS=Q_3+1.5\cdot IQR\)</span></li>
</ul></li>
</ul></li>
<li>Extremo inferior
<ul>
<li>Es el valor extremo inferior más pequeño que se encuentre dentro de:
<ul>
<li><span class="math inline">\(LS=Q_1-1.5\cdot IQR\)</span></li>
</ul></li>
</ul></li>
<li>Cualquier valor fuera de LI y LS es considerado “atípico” y debe estudiarse</li>
</ul>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Ejemplo - Box plot</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div id="htmlwidget-d4506296237d32725be5" style="width:850px;height:600px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-d4506296237d32725be5">{"x":{"visdat":{"5c586814aba":["function () ","plotlyVisDat"]},"cur_data":"5c586814aba","attrs":{"5c586814aba":{"y":{},"boxpoints":"outliers","marker":{"color":"darkred"},"line":{"color":"black"},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"box"}},"layout":{"width":850,"height":600,"margin":{"b":40,"l":60,"t":25,"r":10},"paper_bgcolor":"#F1F5F5","plot_bgcolor":"#F1F5F5","font":{"size":25},"yaxis":{"domain":[0,1],"automargin":true,"title":"Valores","tickfont":{"size":20}},"xaxis":{"domain":[0,1],"automargin":true,"showticklabels":false},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"fillcolor":"rgba(31,119,180,0.5)","y":[73.799999999999997,74.200000000000003,75.099999999999994,75.299999999999997,75.5,75.700000000000003,76.5,76.900000000000006,77.099999999999994,77.200000000000003,77.200000000000003,77.200000000000003],"boxpoints":"outliers","marker":{"color":"darkred","line":{"color":"rgba(31,119,180,1)"}},"line":{"color":"black"},"type":"box","xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div><div class="column" style="width:50%;">
<h3>Importante</h3>
<ul>
<li>Las comillas en “atípico” son importantes, pues no implica que el dato no pertenezca al conjunto de datos.</li>
<li>El dato obtenido puede ser completamente natural, pero debe estudiarse de forma individual al diferir sustancialmente de sus pares.</li>
<li>De nuevo, un dato atípico <span class="hi">no debe eliminarse ni tratarse sin una justificación de peso</span>.</li>
</ul>
</div></div>
</section></section>
<section>
<section class="title-slide slide level1 bloques center">
<h1>Medidas para dos variables cuantitativas y cualitativas</h1>

</section>
<section class="slide level2 bloques">
<h2>Una variable cuantitativa y otra cuantitativa</h2>
<ul>
<li><p>Suponga que usted como analista desea estudiar el rendimiento (%) de algunas máquinas CNC.</p></li>
<li><p>Tiene dos variables</p>
<ul>
<li>Rendimiento: Cuantitativa</li>
<li>Máquinas: Cualitativa</li>
</ul></li>
<li><p>Usted puede hacer grupos y analizar el promedio del rendimiento por máquina. De igual manera puede usar otros estadísticos.</p></li>
<li><p>También puede realizar los gráficos estudiados pero por categorías.</p></li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>Dos variables cuantitativas</h2>
<ul>
<li>Por ejemplo, usted desea estudiar el efecto que tienen los años de experiencia sobre el salario percibido por las personas.</li>
<li>Tiene dos variables cuantitativas:
<ul>
<li>Años de experiencia</li>
<li>Salario percibido</li>
</ul></li>
<li>Todas las técnicas estadísticas estudiadas hasta ahora pueden usarse. Incluyendo visualizaciones.</li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>Dos variables cuantitativas</h2>
<ul>
<li><p>Se introduce una nueva forma de visualización, donde usted puede visualizar y correspondientemente estudiar la relación que existe entre dos variables.</p></li>
<li><p>Este gráfico posiblemente ya lo conoce de cursos de ciencias básicas como química y física, donde se muestra en un eje (<span class="math inline">\(x\)</span>) una variable y en el otro (<span class="math inline">\(y\)</span>), de tal modo que se puede apreciar como se relacionan las mismas.</p></li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>Dos variables cuantitativas</h2>
<div class="columns">
<div class="column img-fit" style="width:50%;">
<p><img data-src="img/xyplot.png"></p>
</div><div class="column" style="width:50%;">
<p>En el gráfico de la izquierda puede encontrar la relación que existe entre el salario promedio mensual y la edad de las personas, clasificadas por género y en general.</p>
</div></div>
</section>
<section class="slide level2 bloques">
<h2>Comunicación tendenciosa o errónea</h2>
<ul>
<li>Parte del comportamiento ético necesario en el quehacer estadístico es comunicar los resultados de forma debida</li>
</ul>
</section>
<section class="slide level2 limpio">
<h2></h2>

<img data-src="img/dificil_leer.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section class="slide level2 limpio">
<h2></h2>

<img data-src="img/malos_porcentajes.jpg" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section class="slide level2 limpio">
<h2></h2>

<img data-src="img/proporciones_malas.jpg" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section class="slide level2 limpio">
<h2></h2>

<img data-src="img/proporciones_malas2.jpg" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section class="slide level2 bloques">
<h2>¿Cómo escoger el gráfico adecuado?</h2>
<ul>
<li>Para escoger el gráfico adecuado puede apoyarse en este <a href="https://www.data-to-viz.com/#explore" target="_blank">enlace</a>.</li>
<li>¿Que hacer y no hacer a la hora de confeccionar un gráfico? Siga este <a href="https://www.data-to-viz.com/caveats.html" target="_blank">enlace</a>.</li>
<li>¿Quiere más ideas para seleccionar un gráfico? Use este <a href="https://datavizcatalogue.com/ES/" target="_blank">enlace</a>.</li>
</ul>
</section>
<section class="slide level2 bloques">
<h2>Bibliografía</h2>
<div class="columns">
<div class="column" style="font-size: 0.8em;">
<ul>
<li>Walpole, R.; Myers, R.; Myers, S. y Ye, K. Probabilidad y estadística para ingeniería y ciencias (9na Edición).
<ul>
<li>Capítulo 1</li>
</ul></li>
<li>Lind, D.; Marchal, W. y Watchen, S. Estadística aplicada a los Negocios y la Economía (15va Edición).
<ul>
<li>Capítulo 2, 3 y 4</li>
</ul></li>
<li>Devore, J. Probabilidad y Estadística para Ingeniería y Ciencias (7ma Edición).
<ul>
<li>Capítulo 2</li>
</ul></li>
<li>Levine, D.; Krehbiel, T.; Berenson, M. Estadística para administración (4ta Edición).
<ul>
<li>Capítulo 2 y 3</li>
</ul></li>
<li>Lock, R.; Lock, P.; Morgan, K.; Lock, E. &amp; Lock, D. Statistics: Unlocking the Power of Data (3rd Edition)
<ul>
<li>Capítulo 2</li>
</ul></li>
<li>Westfall P. H. (2014). Kurtosis as Peakedness, 1905 - 2014. R.I.P. The American statistician, 68(3), 191–195. <a href="https://doi.org/10.1080/00031305.2014.917055" class="uri">https://doi.org/10.1080/00031305.2014.917055</a></li>
</ul>
</div></div>
</section>
<section class="slide level2 center">
<h2>Descripción de datos <br> II-1120 Estadística para Ingeniería Industrial I</h2>
<h3 class="subtitle">Gracias por su atención <br> Steven García Goñi<br><a href="mailto:steven.garciagoni@ucr.ac.cr">steven.garciagoni@ucr.ac.cr</a></h3>
<h3>Dudas o correcciones requeridas pueden solicitarse al correo</h3>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><span class="footer-text">© 2026 <a href="https://stevenggoni.github.io/">Steven García Goñi</a>| <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Licencia CC BY NC 4.0</a></span> <img src="https://stevenggoni.github.io/images/Cuervos_SinFondo-02.png" class="footer-logo"></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1920,

        height: 1080,

        // Factor of the display size that should remain empty around the content
        margin: 5.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    <script>videojs(video_shortcode_videojs_video1);</script>
    

</body></html>